name: Audit dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.22.3'
      - run: make install-tools
      - run: make audit
